### ISSUE TITLE
IPsets not being correctly created

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/kube-router#1]
This code was removed from line 131 of pkg/controllers/netpol/policy.go:

```
                err := ipset.Restore()
                if err != nil {
                        return nil, nil, fmt.Errorf("failed to perform ipset restore: %s", err.Error())
                }
```
That means, inside the for ipFamily, ipset := range npc.ipSetHandlers { loop but outside the for _, policy := range networkPoliciesInfo { loop

Without this code, the ipsets are not created and iptables complains

**Comment by vadorovsky** [comment]
Should be fixed now
