### ISSUE TITLE
Typo: currnetPodIps

### ISSUE THREAD

**Issue by manuelbuil** [k3s-io/kube-router#4]
In pkg/controllers/netpol/policy.go you have the variable currnetPodIps but I guess you mean currentPodIps ;)

**Comment by vadorovsky** [comment]
Actually that typo is present upstream as well, I just didn't notice it when moving things around https://github.com/cloudnativelabs/kube-router/blob/v1.3.2/pkg/controllers/netpol/policy.go#L109

**Comment by vadorovsky** [comment]
But it was fixed later https://github.com/cloudnativelabs/kube-router/blob/master/pkg/controllers/netpol/policy.go#L110

**Comment by vadorovsky** [comment]
Fixed and pushed
